# Generated by Django 4.2 on 2023-09-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0002_ticket_ticketmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketmedia',
            name='media_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticketmedia',
            name='telegram_id',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.PositiveBigIntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviline.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
