# Generated by Django 4.2 on 2023-09-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0003_alter_ticket_customer_alter_ticketmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productproblem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviline.product'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='ticketmedia',
            name='media_type',
            field=models.SmallIntegerField(choices=[(1, 'Photo'), (2, 'Video'), (3, 'Audio'), (4, 'Document'), (5, 'Animation')], default=1),
        ),
        migrations.AlterField(
            model_name='ticketmedia',
            name='telegram_id',
            field=models.CharField(editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketmedia',
            name='ticket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aviline.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aviline.ticket'),
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviline.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
