# Generated by Django 4.2 on 2023-09-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0004_product_is_active_alter_productproblem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproblem',
            name='attachment',
            field=models.URLField(blank=True, null=True, verbose_name='file link attachment'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='aviline.product'),
        ),
    ]
