# Generated by Django 4.2 on 2023-10-07 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0006_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=255)),
                ('attachment', models.URLField(blank=True, null=True, verbose_name='attachment link')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviline.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
