# Generated by Django 4.2 on 2023-11-10 06:37

import aviline.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0009_alter_product_is_subproduct_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productproblem',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id'], 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AddField(
            model_name='product',
            name='attachment',
            field=models.URLField(blank=True, null=True, verbose_name='attachment link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Имя продукта, не более 64 байт (примерно 32 символа кириллицы)', max_length=64, unique=True, validators=[aviline.validators.product_name_lte_64_bytes]),
        ),
    ]
