# Generated by Django 4.2 on 2023-11-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0010_delete_visitor_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attachment',
            field=models.URLField(blank=True, help_text='URL с дополнительной информацией, по умолчанию 200 символов максимум', null=True, verbose_name='attachment link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описание продукта. Выводится в боте', null=True),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
