# Generated by Django 4.2 on 2023-12-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0011_remove_prod_details_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
