# Generated by Django 4.2 on 2024-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviline', '0012_alter_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='telegram_message_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
